# Cloud Build configuration for Growth Engine
# Deploys to Cloud Run with full CI/CD pipeline

steps:
  # Step 1: Run tests
  - name: 'python:3.11'
    id: 'test'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -e ".[dev]"
        pytest tests/ -v --tb=short

  # Step 2: Build container image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/growth-engine:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/growth-engine:latest'
      - '-f'
      - 'Dockerfile'
      - '.'
    waitFor: ['test']

  # Step 3: Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/growth-engine:$COMMIT_SHA'
    waitFor: ['build']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-latest'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/growth-engine:latest'
    waitFor: ['build']

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'growth-engine'
      - '--image'
      - 'gcr.io/$PROJECT_ID/growth-engine:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '3600'
      - '--set-env-vars'
      - 'ENVIRONMENT=production'
      - '--set-secrets'
      - 'DATABASE_URL=database-url:latest,GOOGLE_API_KEY=google-api-key:latest,ANTHROPIC_API_KEY=anthropic-api-key:latest,OPENAI_API_KEY=openai-api-key:latest'
    waitFor: ['push']

  # Step 5: Deploy scheduler service
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-scheduler'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'growth-engine-scheduler'
      - '--image'
      - 'gcr.io/$PROJECT_ID/growth-engine:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--no-allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--command'
      - 'python,-m,src.scheduler'
      - '--set-env-vars'
      - 'ENVIRONMENT=production'
      - '--set-secrets'
      - 'DATABASE_URL=database-url:latest,GOOGLE_API_KEY=google-api-key:latest'
    waitFor: ['push']

substitutions:
  _REGION: us-central1

images:
  - 'gcr.io/$PROJECT_ID/growth-engine:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/growth-engine:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1800s'
