"""
Massive Conferences, Events & Hackathons Database - 200+ Events
"""

TECH_CONFERENCES = {
    # === MAJOR TECH CONFERENCES ===
    "ces": {"url": "https://www.ces.tech", "location": "Las Vegas", "type": "consumer_tech"},
    "web_summit": {"url": "https://websummit.com", "location": "Lisbon", "type": "tech"},
    "collision": {"url": "https://collisionconf.com", "location": "Toronto", "type": "tech"},
    "sxsw": {"url": "https://www.sxsw.com", "location": "Austin", "type": "tech_media"},
    "techcrunch_disrupt": {"url": "https://techcrunch.com/events/tc-disrupt", "location": "San Francisco", "type": "startup"},
    "rise": {"url": "https://riseconf.com", "location": "Hong Kong", "type": "asia_tech"},
    "slush": {"url": "https://www.slush.org", "location": "Helsinki", "type": "startup"},
    "tnw_conference": {"url": "https://thenextweb.com/conference", "location": "Amsterdam", "type": "tech"},
    "dmexco": {"url": "https://dmexco.com", "location": "Cologne", "type": "digital_marketing"},
    "money2020": {"url": "https://us.money2020.com", "location": "Las Vegas", "type": "fintech"},
    "finovate": {"url": "https://informaconnect.com/finovate", "location": "Multiple", "type": "fintech"},
    "dreamforce": {"url": "https://www.salesforce.com/dreamforce", "location": "San Francisco", "type": "enterprise"},
    "oracle_openworld": {"url": "https://www.oracle.com/cloudworld", "location": "Las Vegas", "type": "enterprise"},
    "sapphire": {"url": "https://www.sap.com/events/sapphire.html", "location": "Orlando", "type": "enterprise"},
    "microsoft_ignite": {"url": "https://ignite.microsoft.com", "location": "Multiple", "type": "enterprise"},
    "microsoft_build": {"url": "https://build.microsoft.com", "location": "Seattle", "type": "developer"},
    "google_io": {"url": "https://io.google", "location": "Mountain View", "type": "developer"},
    "google_cloud_next": {"url": "https://cloud.withgoogle.com/next", "location": "San Francisco", "type": "cloud"},
    "apple_wwdc": {"url": "https://developer.apple.com/wwdc", "location": "Cupertino", "type": "developer"},
    "aws_reinvent": {"url": "https://reinvent.awsevents.com", "location": "Las Vegas", "type": "cloud"},
    "github_universe": {"url": "https://githubuniverse.com", "location": "San Francisco", "type": "developer"},
    "gitlab_commit": {"url": "https://about.gitlab.com/events/commit", "location": "Virtual", "type": "developer"},
    "hashiconf": {"url": "https://hashiconf.com", "location": "Multiple", "type": "devops"},
    "kubecon": {"url": "https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america", "location": "Multiple", "type": "devops"},
    "dockercon": {"url": "https://www.docker.com/dockercon", "location": "Multiple", "type": "devops"},
    "devoxx": {"url": "https://www.devoxx.com", "location": "Multiple", "type": "developer"},
    "qcon": {"url": "https://qconferences.com", "location": "Multiple", "type": "developer"},
    "strangeloop": {"url": "https://www.thestrangeloop.com", "location": "St. Louis", "type": "developer"},
    "pycon": {"url": "https://us.pycon.org", "location": "Multiple", "type": "python"},
    "jsconf": {"url": "https://jsconf.com", "location": "Multiple", "type": "javascript"},
    "reactconf": {"url": "https://conf.reactjs.org", "location": "Multiple", "type": "react"},
    "vueconf": {"url": "https://us.vuejs.org", "location": "Multiple", "type": "vue"},
    "rubyconf": {"url": "https://rubyconf.org", "location": "Multiple", "type": "ruby"},
    "railsconf": {"url": "https://railsconf.org", "location": "Multiple", "type": "rails"},
    "gophercon": {"url": "https://www.gophercon.com", "location": "Multiple", "type": "golang"},
    "rustconf": {"url": "https://rustconf.com", "location": "Multiple", "type": "rust"},
    "kotlinconf": {"url": "https://kotlinconf.com", "location": "Multiple", "type": "kotlin"},
    "swiftconf": {"url": "https://swiftconf.com", "location": "Multiple", "type": "swift"},
    "dotnetconf": {"url": "https://www.dotnetconf.net", "location": "Virtual", "type": "dotnet"},
    
    # === AI/ML CONFERENCES ===
    "neurips": {"url": "https://nips.cc", "location": "Multiple", "type": "ai_research"},
    "icml": {"url": "https://icml.cc", "location": "Multiple", "type": "ai_research"},
    "iclr": {"url": "https://iclr.cc", "location": "Multiple", "type": "ai_research"},
    "cvpr": {"url": "https://cvpr.thecvf.com", "location": "Multiple", "type": "computer_vision"},
    "eccv": {"url": "https://eccv.ecva.net", "location": "Multiple", "type": "computer_vision"},
    "iccv": {"url": "https://iccv.thecvf.com", "location": "Multiple", "type": "computer_vision"},
    "acl": {"url": "https://www.aclweb.org/portal", "location": "Multiple", "type": "nlp"},
    "emnlp": {"url": "https://2024.emnlp.org", "location": "Multiple", "type": "nlp"},
    "naacl": {"url": "https://naacl.org", "location": "Multiple", "type": "nlp"},
    "aaai": {"url": "https://www.aaai.org/Conferences", "location": "Multiple", "type": "ai_research"},
    "ijcai": {"url": "https://www.ijcai.org", "location": "Multiple", "type": "ai_research"},
    "kdd": {"url": "https://kdd.org/conferences", "location": "Multiple", "type": "data_mining"},
    "recsys": {"url": "https://recsys.acm.org", "location": "Multiple", "type": "recommender"},
    "wsdm": {"url": "https://www.wsdm-conference.org", "location": "Multiple", "type": "data_mining"},
    "sigir": {"url": "https://sigir.org/sigir2024", "location": "Multiple", "type": "information_retrieval"},
    "www": {"url": "https://www2024.thewebconf.org", "location": "Multiple", "type": "web"},
    "colt": {"url": "https://learningtheory.org", "location": "Multiple", "type": "theory"},
    "aistats": {"url": "https://aistats.org", "location": "Multiple", "type": "ai_stats"},
    "uai": {"url": "https://www.auai.org", "location": "Multiple", "type": "uncertainty"},
    "corl": {"url": "https://www.robot-learning.org", "location": "Multiple", "type": "robotics"},
    "icra": {"url": "https://www.ieee-ras.org/conferences-workshops/fully-sponsored/icra", "location": "Multiple", "type": "robotics"},
    "iros": {"url": "https://www.iros.org", "location": "Multiple", "type": "robotics"},
    "rss": {"url": "https://roboticsconference.org", "location": "Multiple", "type": "robotics"},
    
    # === CYBERSECURITY CONFERENCES ===
    "defcon": {"url": "https://defcon.org", "location": "Las Vegas", "type": "security"},
    "blackhat": {"url": "https://www.blackhat.com", "location": "Las Vegas", "type": "security"},
    "rsa_conference": {"url": "https://www.rsaconference.com", "location": "San Francisco", "type": "security"},
    "bsides": {"url": "http://www.securitybsides.com", "location": "Multiple", "type": "security"},
    "shmoocon": {"url": "https://shmoocon.org", "location": "Washington DC", "type": "security"},
    "ccc": {"url": "https://events.ccc.de", "location": "Germany", "type": "security"},
    "infiltrate": {"url": "https://infiltratecon.com", "location": "Miami", "type": "security"},
    "recon": {"url": "https://recon.cx", "location": "Montreal", "type": "security"},
    "nullcon": {"url": "https://nullcon.net", "location": "Goa", "type": "security"},
    "hitb": {"url": "https://conference.hitb.org", "location": "Multiple", "type": "security"},
    
    # === WEB3/CRYPTO CONFERENCES ===
    "consensus": {"url": "https://consensus.coindesk.com", "location": "Multiple", "type": "crypto"},
    "ethcc": {"url": "https://ethcc.io", "location": "Paris", "type": "ethereum"},
    "devcon": {"url": "https://devcon.org", "location": "Multiple", "type": "ethereum"},
    "eth_denver": {"url": "https://www.ethdenver.com", "location": "Denver", "type": "ethereum"},
    "nftnyc": {"url": "https://www.nft.nyc", "location": "New York", "type": "nft"},
    "blockchain_week": {"url": "https://blockchainweek.com", "location": "Multiple", "type": "blockchain"},
    "token2049": {"url": "https://www.token2049.com", "location": "Singapore", "type": "crypto"},
    "mainnet": {"url": "https://mainnet.events", "location": "New York", "type": "crypto"},
    "permissionless": {"url": "https://blockworks.co/events/permissionless", "location": "Multiple", "type": "defi"},
    "solana_breakpoint": {"url": "https://solana.com/breakpoint", "location": "Multiple", "type": "solana"},
    "cosmoverse": {"url": "https://cosmoverse.org", "location": "Multiple", "type": "cosmos"},
    "avalanche_summit": {"url": "https://www.avalanchesummit.com", "location": "Barcelona", "type": "avalanche"},
    
    # === DATA/ANALYTICS CONFERENCES ===
    "strata_data": {"url": "https://www.oreilly.com/conferences/strata-data.html", "location": "Multiple", "type": "data"},
    "spark_summit": {"url": "https://www.databricks.com/dataaisummit", "location": "San Francisco", "type": "data"},
    "snowflake_summit": {"url": "https://www.snowflake.com/summit", "location": "Las Vegas", "type": "data"},
    "tableau_conference": {"url": "https://www.tableau.com/events/conference", "location": "Las Vegas", "type": "analytics"},
    "looker_join": {"url": "https://join.looker.com", "location": "San Francisco", "type": "analytics"},
    "dbt_coalesce": {"url": "https://coalesce.getdbt.com", "location": "Multiple", "type": "data"},
    "data_council": {"url": "https://www.datacouncil.ai", "location": "Multiple", "type": "data"},
    
    # === PRODUCT/DESIGN ===
    "productcon": {"url": "https://www.productschool.com/productcon", "location": "Multiple", "type": "product"},
    "mind_the_product": {"url": "https://www.mindtheproduct.com/events", "location": "Multiple", "type": "product"},
    "config": {"url": "https://config.figma.com", "location": "San Francisco", "type": "design"},
    "ux_london": {"url": "https://uxlondon.com", "location": "London", "type": "design"},
    "ixda": {"url": "https://interaction.ixda.org", "location": "Multiple", "type": "design"},
    "smashing_conf": {"url": "https://smashingconf.com", "location": "Multiple", "type": "web_design"},
    "awwwards": {"url": "https://conference.awwwards.com", "location": "Multiple", "type": "web_design"},
    "99u": {"url": "https://99u.adobe.com/conference", "location": "New York", "type": "creative"},
    "adobe_max": {"url": "https://max.adobe.com", "location": "Los Angeles", "type": "creative"},
    
    # === STARTUP/ENTREPRENEURSHIP ===
    "ycombinator_demo_day": {"url": "https://www.ycombinator.com/demoday", "location": "San Francisco", "type": "startup"},
    "techstars_demo_day": {"url": "https://www.techstars.com/newsroom/techstars-demo-days", "location": "Multiple", "type": "startup"},
    "startup_grind_global": {"url": "https://www.startupgrind.com/conference", "location": "Silicon Valley", "type": "startup"},
    "indiehackers_meetup": {"url": "https://www.indiehackers.com/meetups", "location": "Multiple", "type": "indie"},
    "microconf": {"url": "https://microconf.com", "location": "Multiple", "type": "saas"},
    "saastr_annual": {"url": "https://www.saastrannual.com", "location": "San Francisco", "type": "saas"},
    "saas_north": {"url": "https://saasnorth.com", "location": "Ottawa", "type": "saas"},
    "how_to_web": {"url": "https://www.howtoweb.co", "location": "Bucharest", "type": "startup"},
    "wolves_summit": {"url": "https://wolvessummit.com", "location": "Multiple", "type": "startup"},
    "arctic15": {"url": "https://arctic15.com", "location": "Helsinki", "type": "startup"},
    "bits_pretzels": {"url": "https://www.bitsandpretzels.com", "location": "Munich", "type": "startup"},
    "noah_conference": {"url": "https://noah-conference.com", "location": "Multiple", "type": "startup"},
    "latitude59": {"url": "https://latitude59.ee", "location": "Tallinn", "type": "startup"},
    "pioneers": {"url": "https://pioneers.io/events", "location": "Vienna", "type": "startup"},
}

ACADEMIC_CONFERENCES = {
    # === COMPUTER SCIENCE ===
    "siggraph": {"url": "https://www.siggraph.org", "field": "graphics"},
    "chi": {"url": "https://chi.acm.org", "field": "hci"},
    "ubicomp": {"url": "https://ubicomp.org", "field": "ubiquitous"},
    "isca": {"url": "https://iscaconf.org", "field": "architecture"},
    "micro": {"url": "https://www.microarch.org", "field": "architecture"},
    "asplos": {"url": "https://asplos-conference.org", "field": "systems"},
    "osdi": {"url": "https://www.usenix.org/conference/osdi", "field": "systems"},
    "sosp": {"url": "https://sosp.org", "field": "systems"},
    "nsdi": {"url": "https://www.usenix.org/conference/nsdi", "field": "networking"},
    "sigcomm": {"url": "https://www.sigcomm.org", "field": "networking"},
    "mobicom": {"url": "https://www.sigmobile.org/mobicom", "field": "mobile"},
    "mobisys": {"url": "https://www.sigmobile.org/mobisys", "field": "mobile"},
    "sensys": {"url": "https://sensys.acm.org", "field": "sensors"},
    "sec": {"url": "https://www.usenix.org/conference/usenixsecurity", "field": "security"},
    "oakland": {"url": "https://www.ieee-security.org/TC/SP-Index.html", "field": "security"},
    "ccs": {"url": "https://www.sigsac.org/ccs", "field": "security"},
    "ndss": {"url": "https://www.ndss-symposium.org", "field": "security"},
    "pldi": {"url": "https://conf.researchr.org/series/pldi", "field": "programming_languages"},
    "popl": {"url": "https://conf.researchr.org/series/popl", "field": "programming_languages"},
    "oopsla": {"url": "https://conf.researchr.org/series/oopsla", "field": "programming_languages"},
    "icse": {"url": "https://conf.researchr.org/series/icse", "field": "software_engineering"},
    "fse": {"url": "https://conf.researchr.org/series/fse", "field": "software_engineering"},
    "ase": {"url": "https://conf.researchr.org/series/ase", "field": "software_engineering"},
    "vldb": {"url": "https://vldb.org", "field": "databases"},
    "sigmod": {"url": "https://sigmod.org", "field": "databases"},
    "icde": {"url": "https://icde.org", "field": "databases"},
    "focs": {"url": "https://focs.computer.org", "field": "theory"},
    "stoc": {"url": "https://www.sigact.org/stoc.html", "field": "theory"},
    "soda": {"url": "https://www.siam.org/conferences/cm/conference/soda24", "field": "algorithms"},
    
    # === OTHER STEM ===
    "agu_fall": {"url": "https://www.agu.org/Fall-Meeting", "field": "geoscience"},
    "acs_national": {"url": "https://www.acs.org/meetings.html", "field": "chemistry"},
    "mrs_fall": {"url": "https://www.mrs.org/meetings-events", "field": "materials"},
    "aps_march": {"url": "https://www.aps.org/meetings/march", "field": "physics"},
    "ieee_vr": {"url": "https://ieeevr.org", "field": "vr"},
    "ismar": {"url": "https://ismar.net", "field": "ar"},
}

HACKATHONS = {
    # === MAJOR HACKATHON PLATFORMS ===
    "devpost": {"url": "https://devpost.com/hackathons", "type": "platform"},
    "mlh": {"url": "https://mlh.io/seasons/2024/events", "type": "platform"},
    "hackathon_com": {"url": "https://www.hackathon.com/event", "type": "platform"},
    "devfolio": {"url": "https://devfolio.co/hackathons", "type": "platform"},
    "hackerearth": {"url": "https://www.hackerearth.com/challenges/hackathon", "type": "platform"},
    "unstop": {"url": "https://unstop.com/hackathons", "type": "platform"},
    "hackalist": {"url": "https://www.hackalist.org", "type": "directory"},
    
    # === NOTABLE HACKATHONS ===
    "hack_mit": {"url": "https://hackmit.org", "location": "MIT", "type": "university"},
    "hack_harvard": {"url": "https://hackharvard.io", "location": "Harvard", "type": "university"},
    "treehacks": {"url": "https://www.treehacks.com", "location": "Stanford", "type": "university"},
    "calhacks": {"url": "https://calhacks.io", "location": "Berkeley", "type": "university"},
    "pennapps": {"url": "https://pennapps.com", "location": "Penn", "type": "university"},
    "hackprinceton": {"url": "https://www.hackprinceton.com", "location": "Princeton", "type": "university"},
    "yhack": {"url": "https://www.yhack.org", "location": "Yale", "type": "university"},
    "hackillinois": {"url": "https://www.hackillinois.org", "location": "UIUC", "type": "university"},
    "hackgt": {"url": "https://hack.gt", "location": "Georgia Tech", "type": "university"},
    "hackduke": {"url": "https://www.hackduke.org", "location": "Duke", "type": "university"},
    "hackrice": {"url": "https://www.hackrice.com", "location": "Rice", "type": "university"},
    "hacktx": {"url": "https://hacktx.com", "location": "UT Austin", "type": "university"},
    "bitcamp": {"url": "https://bit.camp", "location": "UMD", "type": "university"},
    "boilermake": {"url": "https://www.boilermake.org", "location": "Purdue", "type": "university"},
    "mhacks": {"url": "https://mhacks.org", "location": "Michigan", "type": "university"},
    "hackuva": {"url": "https://www.hackuva.io", "location": "UVA", "type": "university"},
    "hackcmu": {"url": "https://www.hackcmu.org", "location": "CMU", "type": "university"},
    "nwplus": {"url": "https://www.nwplus.io", "location": "UBC", "type": "university"},
    "hacklahoma": {"url": "https://www.hacklahoma.org", "location": "Oklahoma", "type": "university"},
    "hackbca": {"url": "https://hackbca.com", "location": "High School", "type": "university"},
    
    # === WEB3 HACKATHONS ===
    "ethglobal": {"url": "https://ethglobal.com/events", "type": "web3"},
    "encode_club": {"url": "https://www.encode.club/hackathons", "type": "web3"},
    "solana_hackathon": {"url": "https://solana.com/hackathon", "type": "web3"},
    "polygon_hackathon": {"url": "https://polygon.technology/ecosystem/hackathons", "type": "web3"},
    "chainlink_hackathon": {"url": "https://chain.link/hackathon", "type": "web3"},
    "nearcon_hackathon": {"url": "https://near.org/hackathons", "type": "web3"},
    "avalanche_hackathon": {"url": "https://www.avax.network/hackathon", "type": "web3"},
    "filecoin_hackathon": {"url": "https://fil.org/hackathons", "type": "web3"},
    
    # === CORPORATE HACKATHONS ===
    "google_hash_code": {"url": "https://codingcompetitions.withgoogle.com/hashcode", "type": "corporate"},
    "google_kick_start": {"url": "https://codingcompetitions.withgoogle.com/kickstart", "type": "corporate"},
    "facebook_hacker_cup": {"url": "https://www.facebook.com/codingcompetitions/hacker-cup", "type": "corporate"},
    "microsoft_imagine_cup": {"url": "https://imaginecup.microsoft.com", "type": "corporate"},
    "aws_game_day": {"url": "https://aws.amazon.com/gameday", "type": "corporate"},
    "ibm_call_for_code": {"url": "https://developer.ibm.com/callforcode", "type": "corporate"},
    "salesforce_hackathon": {"url": "https://developer.salesforce.com/events", "type": "corporate"},
    "twilio_signal": {"url": "https://signal.twilio.com", "type": "corporate"},
    "stripe_ctf": {"url": "https://stripe.com/blog/capture-the-flag-20", "type": "corporate"},
    "mongodb_hackathon": {"url": "https://www.mongodb.com/community/forums/c/events", "type": "corporate"},
}

PROFESSIONAL_EVENTS = {
    # === LEADERSHIP/MANAGEMENT ===
    "ted": {"url": "https://www.ted.com/attend/conferences", "type": "ideas"},
    "ted_global": {"url": "https://www.ted.com/tedglobal", "type": "ideas"},
    "tedx": {"url": "https://www.ted.com/tedx/events", "type": "ideas"},
    "world_economic_forum": {"url": "https://www.weforum.org/events", "type": "leadership"},
    "aspen_ideas": {"url": "https://www.aspenideas.org", "type": "ideas"},
    "fortune_brainstorm": {"url": "https://fortune.com/conferences", "type": "business"},
    "Bloomberg_new_economy": {"url": "https://www.bloombergneweconomy.com", "type": "business"},
    "milken_global": {"url": "https://milkeninstitute.org/events/global-conference", "type": "finance"},
    "dealbook_summit": {"url": "https://nytimes.com/dealbook-summit", "type": "business"},
    "recode_code": {"url": "https://www.vox.com/recode-events", "type": "tech_media"},
    
    # === NETWORKING ===
    "startup_grind": {"url": "https://www.startupgrind.com/events", "type": "networking"},
    "founder_network": {"url": "https://foundersnetwork.com/events", "type": "networking"},
    "eo_events": {"url": "https://www.eonetwork.org/events", "type": "networking"},
    "ypo_events": {"url": "https://www.ypo.org/events", "type": "networking"},
    "chief_events": {"url": "https://www.chief.com/events", "type": "networking"},
    "summit_series": {"url": "https://www.summitseries.com", "type": "networking"},
}

def get_all_event_sources():
    """Return total count and all event sources"""
    total = len(TECH_CONFERENCES) + len(ACADEMIC_CONFERENCES) + len(HACKATHONS) + len(PROFESSIONAL_EVENTS)
    return {
        "total": total,
        "tech_conferences": TECH_CONFERENCES,
        "academic_conferences": ACADEMIC_CONFERENCES,
        "hackathons": HACKATHONS,
        "professional_events": PROFESSIONAL_EVENTS
    }
