"""
Massive Grants & Funding Sources Database - 200+ Grant Programs
"""

GOVERNMENT_GRANTS = {
    # === USA FEDERAL GRANTS ===
    "grants_gov": {"url": "https://www.grants.gov", "country": "USA", "type": "federal"},
    "nsf": {"url": "https://www.nsf.gov/funding", "country": "USA", "type": "research"},
    "nih": {"url": "https://grants.nih.gov/funding/index.htm", "country": "USA", "type": "health"},
    "doe_sbir": {"url": "https://science.osti.gov/sbir/Awards", "country": "USA", "type": "energy"},
    "nasa_sbir": {"url": "https://sbir.nasa.gov/content/nasa-sbir-sttr-awards", "country": "USA", "type": "space"},
    "darpa": {"url": "https://www.darpa.mil/work-with-us/opportunities", "country": "USA", "type": "defense"},
    "arpa_e": {"url": "https://arpa-e.energy.gov/technologies/programs", "country": "USA", "type": "energy"},
    "arpa_h": {"url": "https://arpa-h.gov/research-and-funding", "country": "USA", "type": "health"},
    "nist_sbir": {"url": "https://www.nist.gov/tpo/small-business-innovation-research-program", "country": "USA", "type": "standards"},
    "dod_sbir": {"url": "https://www.dodsbir.net/submissions/portal", "country": "USA", "type": "defense"},
    "usda_sbir": {"url": "https://www.sbir.gov/agencies/usda", "country": "USA", "type": "agriculture"},
    "epa_sbir": {"url": "https://www.epa.gov/sbir", "country": "USA", "type": "environment"},
    "ed_grants": {"url": "https://www2.ed.gov/fund/grants-apply.html", "country": "USA", "type": "education"},
    "sba": {"url": "https://www.sba.gov/funding-programs/grants", "country": "USA", "type": "small_business"},
    "eda": {"url": "https://www.eda.gov/funding", "country": "USA", "type": "economic_development"},
    "commerce_grants": {"url": "https://www.commerce.gov/grants-contracts", "country": "USA", "type": "commerce"},
    "hud_grants": {"url": "https://www.hud.gov/grants", "country": "USA", "type": "housing"},
    "doj_grants": {"url": "https://www.justice.gov/grants", "country": "USA", "type": "justice"},
    "state_dept": {"url": "https://www.state.gov/grants", "country": "USA", "type": "foreign_affairs"},
    "usaid": {"url": "https://www.usaid.gov/work-usaid/resources-for-partners/grants-and-contracts", "country": "USA", "type": "development"},
    "neh": {"url": "https://www.neh.gov/grants", "country": "USA", "type": "humanities"},
    "nea": {"url": "https://www.arts.gov/grants", "country": "USA", "type": "arts"},
    "imls": {"url": "https://www.imls.gov/grants", "country": "USA", "type": "museums_libraries"},
    "samhsa": {"url": "https://www.samhsa.gov/grants", "country": "USA", "type": "mental_health"},
    "cdc": {"url": "https://www.cdc.gov/grants", "country": "USA", "type": "health"},
    
    # === EUROPEAN GRANTS ===
    "horizon_europe": {"url": "https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/programmes/horizon", "country": "EU", "type": "research"},
    "erc_grants": {"url": "https://erc.europa.eu/funding", "country": "EU", "type": "research"},
    "marie_curie": {"url": "https://marie-sklodowska-curie-actions.ec.europa.eu", "country": "EU", "type": "mobility"},
    "erasmus_plus": {"url": "https://erasmus-plus.ec.europa.eu/opportunities", "country": "EU", "type": "education"},
    "eurostars": {"url": "https://www.eurekanetwork.org/countries/germany/eurostars", "country": "EU", "type": "sme"},
    "life_programme": {"url": "https://cinea.ec.europa.eu/programmes/life_en", "country": "EU", "type": "environment"},
    "creative_europe": {"url": "https://culture.ec.europa.eu/creative-europe", "country": "EU", "type": "culture"},
    "digital_europe": {"url": "https://digital-strategy.ec.europa.eu/en/activities/digital-programme", "country": "EU", "type": "digital"},
    "interreg": {"url": "https://interreg.eu/funding-projects", "country": "EU", "type": "regional"},
    "cosme": {"url": "https://ec.europa.eu/growth/smes/cosme_en", "country": "EU", "type": "sme"},
    "innovate_uk": {"url": "https://www.ukri.org/councils/innovate-uk", "country": "UK", "type": "innovation"},
    "wellcome_trust": {"url": "https://wellcome.org/grant-funding", "country": "UK", "type": "health"},
    "leverhulme": {"url": "https://www.leverhulme.ac.uk/funding", "country": "UK", "type": "research"},
    "dfg": {"url": "https://www.dfg.de/en/research_funding", "country": "Germany", "type": "research"},
    "bmbf": {"url": "https://www.bmbf.de/bmbf/en/research/funding.html", "country": "Germany", "type": "research"},
    "anr_france": {"url": "https://anr.fr/en/funding", "country": "France", "type": "research"},
    "bpi_france": {"url": "https://www.bpifrance.com/all-our-solutions", "country": "France", "type": "innovation"},
    "vinnova": {"url": "https://www.vinnova.se/en/apply-for-funding", "country": "Sweden", "type": "innovation"},
    "nwo": {"url": "https://www.nwo.nl/en/calls", "country": "Netherlands", "type": "research"},
    "snf": {"url": "https://www.snf.ch/en/funding", "country": "Switzerland", "type": "research"},
    "fwf": {"url": "https://www.fwf.ac.at/en/research-funding", "country": "Austria", "type": "research"},
    
    # === CANADA ===
    "nserc": {"url": "https://www.nserc-crsng.gc.ca/Professors-Professeurs/Grants-Subs/index_eng.asp", "country": "Canada", "type": "research"},
    "cihr": {"url": "https://cihr-irsc.gc.ca/e/193.html", "country": "Canada", "type": "health"},
    "sshrc": {"url": "https://www.sshrc-crsh.gc.ca/funding-financement/index-eng.aspx", "country": "Canada", "type": "social_sciences"},
    "nrc_irap": {"url": "https://nrc.canada.ca/en/support-technology-innovation", "country": "Canada", "type": "innovation"},
    "cfref": {"url": "https://www.cfref-apogee.gc.ca", "country": "Canada", "type": "excellence"},
    "sr_ed": {"url": "https://www.canada.ca/en/revenue-agency/services/scientific-research-experimental-development-tax-incentive-program.html", "country": "Canada", "type": "rd"},
    "futurpreneur": {"url": "https://www.futurpreneur.ca/en/get-started", "country": "Canada", "type": "entrepreneur"},
    "mitacs": {"url": "https://www.mitacs.ca/en/programs", "country": "Canada", "type": "innovation"},
    
    # === ASIA-PACIFIC ===
    "jsps": {"url": "https://www.jsps.go.jp/english/e-grants", "country": "Japan", "type": "research"},
    "jst": {"url": "https://www.jst.go.jp/EN/operations/research.html", "country": "Japan", "type": "tech"},
    "nedo": {"url": "https://www.nedo.go.jp/english/activities/index.html", "country": "Japan", "type": "innovation"},
    "nsfc": {"url": "https://www.nsfc.gov.cn/english/site_1/index.html", "country": "China", "type": "research"},
    "most_china": {"url": "https://en.most.gov.cn", "country": "China", "type": "tech"},
    "nrf_korea": {"url": "https://www.nrf.re.kr/eng/main", "country": "Korea", "type": "research"},
    "kiat": {"url": "https://www.kiat.or.kr/eng/index.html", "country": "Korea", "type": "innovation"},
    "nrf_singapore": {"url": "https://www.nrf.gov.sg/funding-grants", "country": "Singapore", "type": "research"},
    "astar_grants": {"url": "https://www.a-star.edu.sg/Research/funding-opportunities", "country": "Singapore", "type": "research"},
    "arc_australia": {"url": "https://www.arc.gov.au/funding-research/funding-schemes", "country": "Australia", "type": "research"},
    "nhmrc": {"url": "https://www.nhmrc.gov.au/funding", "country": "Australia", "type": "health"},
    "dst_india": {"url": "https://dst.gov.in/scientific-programmes", "country": "India", "type": "research"},
    "dbt_india": {"url": "https://dbtindia.gov.in/schemes-programmes", "country": "India", "type": "biotech"},
    "startup_india": {"url": "https://www.startupindia.gov.in/content/sih/en/government-schemes.html", "country": "India", "type": "startup"},
    
    # === INTERNATIONAL ORGANIZATIONS ===
    "world_bank": {"url": "https://www.worldbank.org/en/projects-operations/products-and-services/brief/grants", "type": "development"},
    "ifc": {"url": "https://www.ifc.org/wps/wcm/connect/Topics_Ext_Content/IFC_External_Corporate_Site/Solutions", "type": "development"},
    "un_funding": {"url": "https://www.un.org/en/partnerships/trust-funds", "type": "development"},
    "undp_funding": {"url": "https://www.undp.org/funding", "type": "development"},
    "who_grants": {"url": "https://www.who.int/about/funding", "type": "health"},
    "fao_grants": {"url": "https://www.fao.org/partnerships/resource-partners/en", "type": "agriculture"},
    "unicef_funding": {"url": "https://www.unicef.org/partnerships/funding", "type": "children"},
    "unesco_funding": {"url": "https://www.unesco.org/en/partnerships", "type": "education_culture"},
    "gef": {"url": "https://www.thegef.org/projects-operations/database", "type": "environment"},
    "green_climate": {"url": "https://www.greenclimate.fund/projects", "type": "climate"},
    "gcf": {"url": "https://www.greenclimate.fund/how-we-work/funding-projects", "type": "climate"},
    "african_dev_bank": {"url": "https://www.afdb.org/en/projects-and-operations/project-cycle/project-approval", "type": "development"},
    "asian_dev_bank": {"url": "https://www.adb.org/what-we-do/funds", "type": "development"},
    "iadb": {"url": "https://www.iadb.org/en/about-us/how-we-are-organized/funds", "type": "development"},
    "ebrd": {"url": "https://www.ebrd.com/work-with-us/project-finance.html", "type": "development"},
}

FOUNDATION_GRANTS = {
    # === MEGA FOUNDATIONS ===
    "gates_foundation": {"url": "https://www.gatesfoundation.org/about/how-we-work/grant-opportunities", "focus": "global_health"},
    "ford_foundation": {"url": "https://www.fordfoundation.org/work/our-grants", "focus": "social_justice"},
    "rockefeller": {"url": "https://www.rockefellerfoundation.org/grants", "focus": "development"},
    "macarthur": {"url": "https://www.macfound.org/grants", "focus": "general"},
    "carnegie": {"url": "https://www.carnegie.org/grants", "focus": "education"},
    "kellogg": {"url": "https://www.wkkf.org/grants", "focus": "children"},
    "hewlett": {"url": "https://hewlett.org/grants", "focus": "environment"},
    "packard": {"url": "https://www.packard.org/grants-and-investments", "focus": "conservation"},
    "moore": {"url": "https://www.moore.org/grants", "focus": "science"},
    "bloomberg": {"url": "https://www.bloomberg.org/grants", "focus": "cities"},
    "mellon": {"url": "https://mellon.org/grants", "focus": "humanities"},
    "simons": {"url": "https://www.simonsfoundation.org/funding-opportunities", "focus": "science"},
    "koch": {"url": "https://www.charleskochfoundation.org/apply-for-grant", "focus": "society"},
    "walton": {"url": "https://www.waltonfamilyfoundation.org/grants", "focus": "education"},
    "lumina": {"url": "https://www.luminafoundation.org/our-grants", "focus": "education"},
    "kresge": {"url": "https://kresge.org/grants", "focus": "community"},
    "casey": {"url": "https://www.aecf.org/work/what-we-fund", "focus": "children"},
    "arnold": {"url": "https://www.arnoldventures.org/grants", "focus": "criminal_justice"},
    
    # === TECH FOUNDATIONS ===
    "google_org": {"url": "https://www.google.org/our-work", "focus": "tech_for_good"},
    "microsoft_ai_good": {"url": "https://www.microsoft.com/en-us/ai/ai-for-good", "focus": "ai"},
    "aws_credits": {"url": "https://aws.amazon.com/government-education/nonprofits/programs", "focus": "cloud"},
    "salesforce_foundation": {"url": "https://www.salesforce.org/nonprofit", "focus": "nonprofit"},
    "facebook_grants": {"url": "https://socialimpact.facebook.com/grants", "focus": "community"},
    "twitter_grants": {"url": "https://about.twitter.com/en/who-we-are/twitter-for-good", "focus": "social"},
    "ibm_grants": {"url": "https://www.ibm.org/initiatives", "focus": "tech"},
    "cisco_foundation": {"url": "https://www.cisco.com/c/en/us/about/csr/community/nonprofits.html", "focus": "tech"},
    "intel_foundation": {"url": "https://www.intel.com/content/www/us/en/corporate-responsibility/intel-foundation.html", "focus": "stem"},
    "qualcomm_foundation": {"url": "https://www.qualcomm.com/company/corporate-responsibility/qualcomm-foundation", "focus": "stem"},
    "dell_foundation": {"url": "https://www.delltechnologies.com/en-us/corporate/social-impact.htm", "focus": "education"},
    "nvidia_foundation": {"url": "https://www.nvidia.com/en-us/foundation", "focus": "ai"},
    "stripe_climate": {"url": "https://stripe.com/climate", "focus": "climate"},
    "github_sponsors": {"url": "https://github.com/sponsors", "focus": "open_source"},
    "mozilla_foundation": {"url": "https://foundation.mozilla.org/en/what-we-fund", "focus": "internet"},
    "ethereum_foundation": {"url": "https://ethereum.org/en/community/grants", "focus": "web3"},
    "algorand_foundation": {"url": "https://algorand.foundation/grants-program", "focus": "blockchain"},
    "solana_foundation": {"url": "https://solana.org/grants", "focus": "blockchain"},
    "near_grants": {"url": "https://near.org/grants", "focus": "blockchain"},
    "polkadot_grants": {"url": "https://grants.web3.foundation", "focus": "blockchain"},
    
    # === CLIMATE & ENVIRONMENT ===
    "bezos_earth_fund": {"url": "https://www.bezosearthfund.org", "focus": "climate"},
    "ceres": {"url": "https://www.ceres.org", "focus": "sustainability"},
    "energy_foundation": {"url": "https://www.ef.org/grants", "focus": "energy"},
    "climate_works": {"url": "https://www.climateworks.org/grants", "focus": "climate"},
    "ocean_foundation": {"url": "https://oceanfdn.org/grants", "focus": "ocean"},
    "patagonia_grants": {"url": "https://www.patagonia.com/how-we-fund", "focus": "environment"},
    "11th_hour": {"url": "https://11thhourproject.org/grantmaking", "focus": "sustainability"},
    "wilburforce": {"url": "https://wilburforce.org/grants", "focus": "conservation"},
    "nature_conservancy": {"url": "https://www.nature.org/en-us/about-us/who-we-are/how-we-work/working-with-companies", "focus": "conservation"},
    "wwf_grants": {"url": "https://www.worldwildlife.org/partnerships/corporate-partnerships", "focus": "wildlife"},
    "rainforest_foundation": {"url": "https://rainforestfoundation.org/grants", "focus": "rainforest"},
    "sierra_club": {"url": "https://www.sierraclub.org/foundation/grants", "focus": "environment"},
    
    # === HEALTH ===
    "hhmi": {"url": "https://www.hhmi.org/programs", "focus": "biomedical"},
    "wellcome_trust": {"url": "https://wellcome.org/grant-funding", "focus": "health"},
    "robert_wood_johnson": {"url": "https://www.rwjf.org/en/how-we-work/grants-explorer.html", "focus": "health"},
    "kaiser": {"url": "https://about.kaiserpermanente.org/community-health/about-community-health/grants", "focus": "health"},
    "blue_shield": {"url": "https://blueshieldcafoundation.org/grants", "focus": "health"},
    "california_endowment": {"url": "https://www.calendow.org/grants", "focus": "health"},
    "commonwealth_fund": {"url": "https://www.commonwealthfund.org/grants", "focus": "health"},
    "aetna_foundation": {"url": "https://www.aetna-foundation.org", "focus": "health"},
    "cvs_foundation": {"url": "https://www.cvshealth.com/social-responsibility/our-giving/foundation-grants", "focus": "health"},
    
    # === SOCIAL IMPACT ===
    "open_society": {"url": "https://www.opensocietyfoundations.org/grants", "focus": "human_rights"},
    "omidyar": {"url": "https://omidyar.com/our-work", "focus": "social_impact"},
    "skoll": {"url": "https://skoll.org/skoll-awards", "focus": "social_entrepreneurship"},
    "ashoka_grants": {"url": "https://www.ashoka.org/en-us/funding", "focus": "social_entrepreneurship"},
    "echoing_green": {"url": "https://echoinggreen.org/fellowship", "focus": "social_entrepreneurship"},
    "draper_richards": {"url": "https://www.dfrkaplanfoundation.org/social-entrepreneurs", "focus": "social_entrepreneurship"},
    "mulago": {"url": "https://www.mulagofoundation.org/what-we-look-for", "focus": "poverty"},
    "acumen_fund": {"url": "https://acumen.org/apply", "focus": "poverty"},
    "schwab": {"url": "https://www.schwabfound.org", "focus": "social_entrepreneurship"},
    "unreasonable_impact": {"url": "https://unreasonablegroup.com/ventures/apply", "focus": "impact"},
    
    # === ARTS & CULTURE ===
    "nea_grants": {"url": "https://www.arts.gov/grants", "focus": "arts"},
    "knight_foundation": {"url": "https://knightfoundation.org/grants", "focus": "journalism_arts"},
    "jerome": {"url": "https://www.jeromefdn.org/apply", "focus": "arts"},
    "creative_capital": {"url": "https://creative-capital.org/apply", "focus": "arts"},
    "map_fund": {"url": "https://mapfund.org", "focus": "performing_arts"},
    "doris_duke": {"url": "https://www.dorisduke.org/grants", "focus": "arts"},
    "andy_warhol": {"url": "https://warholfoundation.org/grant-programs", "focus": "visual_arts"},
    "surdna": {"url": "https://surdna.org/grants", "focus": "arts"},
    "pew_center_arts": {"url": "https://www.pewcenterarts.org/grants-fellowships", "focus": "arts"},
    
    # === YOUTH & EDUCATION ===
    "spencer": {"url": "https://www.spencer.org/grants", "focus": "education_research"},
    "joyce": {"url": "https://www.joycefdn.org/grants", "focus": "education"},
    "ewing_marion_kauffman": {"url": "https://www.kauffman.org/grants", "focus": "entrepreneurship_education"},
    "jack_kent_cooke": {"url": "https://www.jkcf.org/grants", "focus": "education"},
    "nike_foundation": {"url": "https://about.nike.com/en/impact/community", "focus": "youth"},
    "tiger_foundation": {"url": "https://www.tigerfoundation.org/grants", "focus": "youth"},
    "new_profit": {"url": "https://www.newprofit.org/portfolio", "focus": "education"},
    "stand_together": {"url": "https://standtogether.org/partners", "focus": "education"},
}

CORPORATE_GRANTS = {
    # === INNOVATION PROGRAMS ===
    "google_research_awards": {"url": "https://research.google/outreach/research-scholar-program", "focus": "research"},
    "google_for_startups": {"url": "https://startup.google.com", "focus": "startups"},
    "microsoft_research_grants": {"url": "https://www.microsoft.com/en-us/research/academic-programs", "focus": "research"},
    "microsoft_for_startups": {"url": "https://startups.microsoft.com", "focus": "startups"},
    "aws_activate": {"url": "https://aws.amazon.com/activate", "focus": "startups"},
    "aws_research_credits": {"url": "https://aws.amazon.com/government-education/research-and-technical-computing/research-credits", "focus": "research"},
    "nvidia_inception": {"url": "https://www.nvidia.com/en-us/deep-learning-ai/startups", "focus": "ai_startups"},
    "nvidia_academic": {"url": "https://developer.nvidia.com/academic_gpu_seeding", "focus": "research"},
    "intel_ignite": {"url": "https://ignite.intel.com", "focus": "startups"},
    "ibm_global_entrepreneur": {"url": "https://www.ibm.com/partnerworld/startup", "focus": "startups"},
    "oracle_for_startups": {"url": "https://www.oracle.com/startup", "focus": "startups"},
    "stripe_atlas": {"url": "https://stripe.com/atlas", "focus": "startups"},
    "hubspot_for_startups": {"url": "https://www.hubspot.com/startups", "focus": "startups"},
    "zendesk_for_startups": {"url": "https://www.zendesk.com/startups", "focus": "startups"},
    "notion_for_startups": {"url": "https://www.notion.so/startups", "focus": "startups"},
    "segment_startup_program": {"url": "https://segment.com/industry/startups", "focus": "startups"},
    "airtable_for_startups": {"url": "https://www.airtable.com/startups", "focus": "startups"},
    "brex_for_startups": {"url": "https://www.brex.com/startups", "focus": "fintech"},
    "freshworks_startup": {"url": "https://www.freshworks.com/partners/startup-program", "focus": "startups"},
    "digitalocean_hatch": {"url": "https://www.digitalocean.com/hatch", "focus": "startups"},
}

def get_all_grant_sources():
    """Return total count and all grant sources"""
    total = len(GOVERNMENT_GRANTS) + len(FOUNDATION_GRANTS) + len(CORPORATE_GRANTS)
    return {
        "total": total,
        "government": GOVERNMENT_GRANTS,
        "foundations": FOUNDATION_GRANTS,
        "corporate": CORPORATE_GRANTS
    }
