"""
Massive Job Board Sources Database - 200+ Job Platforms
"""

JOB_BOARDS = {
    # === GLOBAL TECH JOB BOARDS ===
    "linkedin": {"url": "https://www.linkedin.com/jobs", "category": "general", "region": "global"},
    "indeed": {"url": "https://www.indeed.com", "category": "general", "region": "global"},
    "glassdoor": {"url": "https://www.glassdoor.com/Job", "category": "general", "region": "global"},
    "monster": {"url": "https://www.monster.com", "category": "general", "region": "global"},
    "ziprecruiter": {"url": "https://www.ziprecruiter.com", "category": "general", "region": "global"},
    "careerbuilder": {"url": "https://www.careerbuilder.com", "category": "general", "region": "global"},
    "simplyhired": {"url": "https://www.simplyhired.com", "category": "general", "region": "global"},
    "dice": {"url": "https://www.dice.com", "category": "tech", "region": "global"},
    "stackoverflow_jobs": {"url": "https://stackoverflow.com/jobs", "category": "tech", "region": "global"},
    "github_jobs": {"url": "https://jobs.github.com", "category": "tech", "region": "global"},
    
    # === REMOTE-FIRST JOB BOARDS ===
    "remoteok": {"url": "https://remoteok.com", "category": "remote", "region": "global"},
    "weworkremotely": {"url": "https://weworkremotely.com", "category": "remote", "region": "global"},
    "remoteco": {"url": "https://remote.co/remote-jobs", "category": "remote", "region": "global"},
    "flexjobs": {"url": "https://www.flexjobs.com", "category": "remote", "region": "global"},
    "justremote": {"url": "https://justremote.co", "category": "remote", "region": "global"},
    "remoteleaf": {"url": "https://remoteleaf.com", "category": "remote", "region": "global"},
    "remotive": {"url": "https://remotive.com", "category": "remote", "region": "global"},
    "nodesk": {"url": "https://nodesk.co/remote-jobs", "category": "remote", "region": "global"},
    "workingnomads": {"url": "https://www.workingnomads.com/jobs", "category": "remote", "region": "global"},
    "remotehub": {"url": "https://remotehub.com", "category": "remote", "region": "global"},
    "letsworkremotely": {"url": "https://www.letsworkremotely.com", "category": "remote", "region": "global"},
    "remoters": {"url": "https://remoters.net/jobs", "category": "remote", "region": "global"},
    "europeremotely": {"url": "https://europeremotely.com", "category": "remote", "region": "europe"},
    "remotefront": {"url": "https://remotefront.io", "category": "remote", "region": "global"},
    "dailyremote": {"url": "https://dailyremote.com", "category": "remote", "region": "global"},
    "remote4me": {"url": "https://remote4me.com", "category": "remote", "region": "global"},
    "outsourcely": {"url": "https://www.outsourcely.com", "category": "remote", "region": "global"},
    "skipthedrive": {"url": "https://www.skipthedrive.com", "category": "remote", "region": "global"},
    "pangian": {"url": "https://pangian.com/job-travel-remote", "category": "remote", "region": "global"},
    "arc_dev": {"url": "https://arc.dev/remote-jobs", "category": "remote", "region": "global"},
    "himalayas": {"url": "https://himalayas.app/jobs", "category": "remote", "region": "global"},
    "dynamitejobs": {"url": "https://dynamitejobs.com", "category": "remote", "region": "global"},
    "remote_io": {"url": "https://www.remote.io", "category": "remote", "region": "global"},
    "jobspresso": {"url": "https://jobspresso.co", "category": "remote", "region": "global"},
    "virtualvocations": {"url": "https://www.virtualvocations.com", "category": "remote", "region": "global"},
    "rat_race_rebellion": {"url": "https://ratracerebellion.com", "category": "remote", "region": "global"},
    
    # === STARTUP JOB BOARDS ===
    "wellfound": {"url": "https://wellfound.com/jobs", "category": "startup", "region": "global"},
    "ycombinator_jobs": {"url": "https://www.ycombinator.com/jobs", "category": "startup", "region": "global"},
    "workatastartup": {"url": "https://www.workatastartup.com", "category": "startup", "region": "global"},
    "startupers": {"url": "https://www.startupers.com", "category": "startup", "region": "global"},
    "startup_jobs": {"url": "https://startup.jobs", "category": "startup", "region": "global"},
    "f6s_jobs": {"url": "https://www.f6s.com/jobs", "category": "startup", "region": "global"},
    "underdog_io": {"url": "https://underdog.io", "category": "startup", "region": "global"},
    "hired": {"url": "https://hired.com", "category": "startup", "region": "global"},
    "triplebyte": {"url": "https://triplebyte.com", "category": "startup", "region": "global"},
    "techjobsforgood": {"url": "https://www.techjobsforgood.com", "category": "startup", "region": "global"},
    "ventureloop": {"url": "https://www.ventureloop.com", "category": "startup", "region": "global"},
    "betalist_jobs": {"url": "https://betalist.com/jobs", "category": "startup", "region": "global"},
    "productHunt_jobs": {"url": "https://www.producthunt.com/jobs", "category": "startup", "region": "global"},
    "launchwaystartups": {"url": "https://www.launchwaystartups.com/jobs", "category": "startup", "region": "global"},
    
    # === AI/ML SPECIALIZED ===
    "ai_jobs": {"url": "https://ai-jobs.net", "category": "ai_ml", "region": "global"},
    "ml_jobs_list": {"url": "https://mljobslist.com", "category": "ai_ml", "region": "global"},
    "deep_learning_jobs": {"url": "https://www.deeplearning.ai/jobs", "category": "ai_ml", "region": "global"},
    "ai_jobs_board": {"url": "https://aijobsboard.com", "category": "ai_ml", "region": "global"},
    "kaggle_jobs": {"url": "https://www.kaggle.com/jobs", "category": "ai_ml", "region": "global"},
    "datascience_jobs": {"url": "https://datasciencejobs.com", "category": "ai_ml", "region": "global"},
    "analyticsvidhya": {"url": "https://www.analyticsvidhya.com/jobs", "category": "ai_ml", "region": "global"},
    "kdnuggets": {"url": "https://www.kdnuggets.com/jobs", "category": "ai_ml", "region": "global"},
    "bigdatajobs": {"url": "https://www.bigdatajobs.com", "category": "ai_ml", "region": "global"},
    "dataelixir": {"url": "https://dataelixir.com/jobs", "category": "ai_ml", "region": "global"},
    "ai_accelerator": {"url": "https://aiacceleratorp.com/ai-jobs", "category": "ai_ml", "region": "global"},
    "towardsdatascience_jobs": {"url": "https://jobs.towardsdatascience.com", "category": "ai_ml", "region": "global"},
    
    # === WEB3/CRYPTO ===
    "cryptojobslist": {"url": "https://cryptojobslist.com", "category": "web3", "region": "global"},
    "web3_careers": {"url": "https://web3.career", "category": "web3", "region": "global"},
    "cryptocurrencyjobs": {"url": "https://cryptocurrencyjobs.co", "category": "web3", "region": "global"},
    "pompcryptojobs": {"url": "https://pompcryptojobs.com", "category": "web3", "region": "global"},
    "crypto_jobs_daily": {"url": "https://www.cryptojobsdaily.com", "category": "web3", "region": "global"},
    "defi_jobs": {"url": "https://www.defi.jobs", "category": "web3", "region": "global"},
    "useweb3": {"url": "https://www.useweb3.xyz/jobs", "category": "web3", "region": "global"},
    "blockchain_jobs": {"url": "https://blockchainjobz.com", "category": "web3", "region": "global"},
    "ethlance": {"url": "https://ethlance.com", "category": "web3", "region": "global"},
    "crypto_recruit": {"url": "https://www.cryptorecruit.com", "category": "web3", "region": "global"},
    "blockew": {"url": "https://blockew.com", "category": "web3", "region": "global"},
    "daojobs": {"url": "https://daojobs.xyz", "category": "web3", "region": "global"},
    "nft_jobs": {"url": "https://nftjobs.io", "category": "web3", "region": "global"},
    
    # === DESIGN/UX ===
    "dribbble_jobs": {"url": "https://dribbble.com/jobs", "category": "design", "region": "global"},
    "behance_jobs": {"url": "https://www.behance.net/joblist", "category": "design", "region": "global"},
    "uxjobsboard": {"url": "https://www.uxjobsboard.com", "category": "design", "region": "global"},
    "coroflot": {"url": "https://www.coroflot.com/jobs", "category": "design", "region": "global"},
    "authentic_jobs": {"url": "https://authenticjobs.com", "category": "design", "region": "global"},
    "krop": {"url": "https://www.krop.com", "category": "design", "region": "global"},
    "designjobs_board": {"url": "https://www.designjobsboard.com", "category": "design", "region": "global"},
    "uxdesignjobs": {"url": "https://uxdesignjobs.co", "category": "design", "region": "global"},
    "awwwards_jobs": {"url": "https://www.awwwards.com/jobs", "category": "design", "region": "global"},
    "smashingmagazine_jobs": {"url": "https://jobs.smashingmagazine.com", "category": "design", "region": "global"},
    "workingnotworking": {"url": "https://workingnotworking.com", "category": "design", "region": "global"},
    
    # === DEVELOPER-SPECIFIC ===
    "hashjob": {"url": "https://www.hashjob.com", "category": "developer", "region": "global"},
    "angular_jobs": {"url": "https://angularjobs.com", "category": "developer", "region": "global"},
    "react_jobs": {"url": "https://reactjsjob.com", "category": "developer", "region": "global"},
    "vue_jobs": {"url": "https://vuejobs.com", "category": "developer", "region": "global"},
    "python_jobs": {"url": "https://www.python.org/jobs", "category": "developer", "region": "global"},
    "ruby_jobs": {"url": "https://www.rubyjobboard.com", "category": "developer", "region": "global"},
    "golangjob": {"url": "https://www.golangprojects.com", "category": "developer", "region": "global"},
    "rust_jobs": {"url": "https://rustjobs.dev", "category": "developer", "region": "global"},
    "java_jobs": {"url": "https://javajobs.co", "category": "developer", "region": "global"},
    "dotnet_jobs": {"url": "https://dotnetjobs.io", "category": "developer", "region": "global"},
    "ios_dev_jobs": {"url": "https://iosdevjobs.com", "category": "developer", "region": "global"},
    "android_jobs": {"url": "https://androidjobs.io", "category": "developer", "region": "global"},
    "larajobs": {"url": "https://larajobs.com", "category": "developer", "region": "global"},
    "djangojobs": {"url": "https://djangojobs.net", "category": "developer", "region": "global"},
    "railsjobs": {"url": "https://www.railsjobs.com", "category": "developer", "region": "global"},
    "nodesk_dev": {"url": "https://nodesk.co", "category": "developer", "region": "global"},
    "devops_jobs": {"url": "https://devopsjobs.io", "category": "developer", "region": "global"},
    "cloud_jobs": {"url": "https://cloudjobs.io", "category": "developer", "region": "global"},
    "kubernetes_jobs": {"url": "https://kube.careers", "category": "developer", "region": "global"},
    "sre_jobs": {"url": "https://srecareer.com", "category": "developer", "region": "global"},
    
    # === CYBERSECURITY ===
    "cybersecjobs": {"url": "https://www.cybersecjobs.com", "category": "security", "region": "global"},
    "infosec_jobs": {"url": "https://infosec-jobs.com", "category": "security", "region": "global"},
    "cybersecurity_jobs": {"url": "https://www.cybersecurity-jobs.com", "category": "security", "region": "global"},
    "netsecjobs": {"url": "https://netsecjobs.com", "category": "security", "region": "global"},
    "hackerjobs": {"url": "https://hackerjobs.com", "category": "security", "region": "global"},
    
    # === FINTECH ===
    "fintech_jobs": {"url": "https://www.fintechjobs.io", "category": "fintech", "region": "global"},
    "bankless_jobs": {"url": "https://bankless.pallet.com/jobs", "category": "fintech", "region": "global"},
    "finextra_jobs": {"url": "https://www.finextra.com/jobs", "category": "fintech", "region": "global"},
    "efinancialcareers": {"url": "https://www.efinancialcareers.com", "category": "fintech", "region": "global"},
    
    # === GAMING ===
    "hitmarker": {"url": "https://hitmarker.net", "category": "gaming", "region": "global"},
    "gamedev_jobs": {"url": "https://gamedev.jobs", "category": "gaming", "region": "global"},
    "gamesindustry_jobs": {"url": "https://jobs.gamesindustry.biz", "category": "gaming", "region": "global"},
    "gamasutra_jobs": {"url": "https://jobs.gamasutra.com", "category": "gaming", "region": "global"},
    "work_with_indies": {"url": "https://workwithindies.com", "category": "gaming", "region": "global"},
    
    # === USA REGIONAL ===
    "usa_jobs_gov": {"url": "https://www.usajobs.gov", "category": "government", "region": "usa"},
    "builtin": {"url": "https://builtin.com/jobs", "category": "tech", "region": "usa"},
    "builtin_nyc": {"url": "https://www.builtinnyc.com/jobs", "category": "tech", "region": "usa"},
    "builtin_la": {"url": "https://www.builtinla.com/jobs", "category": "tech", "region": "usa"},
    "builtin_sf": {"url": "https://www.builtinsf.com/jobs", "category": "tech", "region": "usa"},
    "builtin_chicago": {"url": "https://www.builtinchicago.org/jobs", "category": "tech", "region": "usa"},
    "builtin_boston": {"url": "https://www.builtinboston.com/jobs", "category": "tech", "region": "usa"},
    "builtin_colorado": {"url": "https://www.builtincolorado.com/jobs", "category": "tech", "region": "usa"},
    "builtin_seattle": {"url": "https://www.builtinseattle.com/jobs", "category": "tech", "region": "usa"},
    "builtin_austin": {"url": "https://www.builtinaustin.com/jobs", "category": "tech", "region": "usa"},
    
    # === EUROPE ===
    "eurojobs": {"url": "https://www.eurojobs.com", "category": "general", "region": "europe"},
    "jobs_eu": {"url": "https://www.jobs.eu", "category": "general", "region": "europe"},
    "berlinstartupjobs": {"url": "https://berlinstartupjobs.com", "category": "startup", "region": "europe"},
    "germantechjobs": {"url": "https://germantechjobs.de", "category": "tech", "region": "europe"},
    "swissdev_jobs": {"url": "https://swissdevjobs.ch", "category": "tech", "region": "europe"},
    "landing_jobs": {"url": "https://landing.jobs", "category": "tech", "region": "europe"},
    "honeypot": {"url": "https://www.honeypot.io", "category": "tech", "region": "europe"},
    "relocate_me": {"url": "https://relocate.me", "category": "tech", "region": "europe"},
    "cwjobs": {"url": "https://www.cwjobs.co.uk", "category": "tech", "region": "uk"},
    "technojobs": {"url": "https://www.technojobs.co.uk", "category": "tech", "region": "uk"},
    "irishjobs": {"url": "https://www.irishjobs.ie", "category": "general", "region": "europe"},
    "jobsineire": {"url": "https://www.jobsineire.ie", "category": "tech", "region": "europe"},
    "nordic_jobs": {"url": "https://www.nordicjobs.com", "category": "general", "region": "europe"},
    "the_hub": {"url": "https://thehub.io", "category": "startup", "region": "europe"},
    "arbeitnow": {"url": "https://arbeitnow.com", "category": "general", "region": "europe"},
    "jobs_in_network": {"url": "https://jobsinnetwork.com", "category": "tech", "region": "europe"},
    
    # === ASIA ===
    "jobsdb": {"url": "https://www.jobsdb.com", "category": "general", "region": "asia"},
    "techinasia_jobs": {"url": "https://www.techinasia.com/jobs", "category": "tech", "region": "asia"},
    "e27_jobs": {"url": "https://e27.co/jobs", "category": "startup", "region": "asia"},
    "singapore_jobs": {"url": "https://www.singaporejobs.com", "category": "general", "region": "asia"},
    "mycareersfuture": {"url": "https://www.mycareersfuture.gov.sg", "category": "general", "region": "asia"},
    "glints": {"url": "https://glints.com", "category": "tech", "region": "asia"},
    "indeed_india": {"url": "https://www.indeed.co.in", "category": "general", "region": "asia"},
    "naukri": {"url": "https://www.naukri.com", "category": "general", "region": "asia"},
    "instahyre": {"url": "https://www.instahyre.com", "category": "tech", "region": "asia"},
    "angel_india": {"url": "https://angel.co/india/jobs", "category": "startup", "region": "asia"},
    "hasjob": {"url": "https://hasjob.co", "category": "tech", "region": "asia"},
    "cutshort": {"url": "https://cutshort.io", "category": "tech", "region": "asia"},
    "hirist": {"url": "https://www.hirist.com", "category": "tech", "region": "asia"},
    "japanjobs": {"url": "https://japan-dev.com", "category": "tech", "region": "asia"},
    "tokyodev": {"url": "https://www.tokyodev.com", "category": "tech", "region": "asia"},
    "daijob": {"url": "https://www.daijob.com", "category": "general", "region": "asia"},
    "gaijinpot": {"url": "https://jobs.gaijinpot.com", "category": "general", "region": "asia"},
    "jobkorea": {"url": "https://www.jobkorea.co.kr", "category": "general", "region": "asia"},
    "saramin": {"url": "https://www.saramin.co.kr", "category": "general", "region": "asia"},
    "104_taiwan": {"url": "https://www.104.com.tw", "category": "general", "region": "asia"},
    "zhaopin": {"url": "https://www.zhaopin.com", "category": "general", "region": "asia"},
    "liepin": {"url": "https://www.liepin.com", "category": "general", "region": "asia"},
    "boss_zhipin": {"url": "https://www.zhipin.com", "category": "general", "region": "asia"},
    
    # === MIDDLE EAST ===
    "bayt": {"url": "https://www.bayt.com", "category": "general", "region": "middle_east"},
    "gulftalent": {"url": "https://www.gulftalent.com", "category": "general", "region": "middle_east"},
    "naukrigulf": {"url": "https://www.naukrigulf.com", "category": "general", "region": "middle_east"},
    "dubizzle_jobs": {"url": "https://dubai.dubizzle.com/jobs", "category": "general", "region": "middle_east"},
    "wuzzuf": {"url": "https://wuzzuf.net", "category": "general", "region": "middle_east"},
    
    # === LATIN AMERICA ===
    "getonbrd": {"url": "https://www.getonbrd.com", "category": "tech", "region": "latam"},
    "computrabajo": {"url": "https://www.computrabajo.com", "category": "general", "region": "latam"},
    "indeed_brazil": {"url": "https://www.indeed.com.br", "category": "general", "region": "latam"},
    "trampos": {"url": "https://trampos.co", "category": "tech", "region": "latam"},
    "bumeran": {"url": "https://www.bumeran.com", "category": "general", "region": "latam"},
    "torre": {"url": "https://torre.co", "category": "tech", "region": "latam"},
    "trabajando": {"url": "https://www.trabajando.com", "category": "general", "region": "latam"},
    
    # === CANADA/AUSTRALIA ===
    "workopolis": {"url": "https://www.workopolis.com", "category": "general", "region": "canada"},
    "jobboom": {"url": "https://www.jobboom.com", "category": "general", "region": "canada"},
    "eluta": {"url": "https://www.eluta.ca", "category": "general", "region": "canada"},
    "seek": {"url": "https://www.seek.com.au", "category": "general", "region": "australia"},
    "jora": {"url": "https://au.jora.com", "category": "general", "region": "australia"},
    "adzuna_au": {"url": "https://www.adzuna.com.au", "category": "general", "region": "australia"},
    
    # === NONPROFIT/SOCIAL IMPACT ===
    "idealist": {"url": "https://www.idealist.org", "category": "nonprofit", "region": "global"},
    "devex_jobs": {"url": "https://www.devex.com/jobs", "category": "nonprofit", "region": "global"},
    "reliefweb_jobs": {"url": "https://reliefweb.int/jobs", "category": "nonprofit", "region": "global"},
    "80000hours": {"url": "https://80000hours.org/job-board", "category": "nonprofit", "region": "global"},
    "workforgood": {"url": "https://www.workforgood.org", "category": "nonprofit", "region": "global"},
    "philanthropy_jobs": {"url": "https://www.philanthropynewsdigest.org/jobs", "category": "nonprofit", "region": "global"},
    "escoffices_jobs": {"url": "https://www.escoffices.jobs", "category": "nonprofit", "region": "global"},
    "impactpool": {"url": "https://www.impactpool.org", "category": "nonprofit", "region": "global"},
    
    # === ACADEMIC/RESEARCH ===
    "academicjobsonline": {"url": "https://academicjobsonline.org", "category": "academic", "region": "global"},
    "higheredjobs": {"url": "https://www.higheredjobs.com", "category": "academic", "region": "global"},
    "insidehighered_jobs": {"url": "https://careers.insidehighered.com", "category": "academic", "region": "global"},
    "chronicle_vitae": {"url": "https://jobs.chronicle.com", "category": "academic", "region": "global"},
    "timeshighered_jobs": {"url": "https://www.timeshighereducation.com/unijobs", "category": "academic", "region": "global"},
    "nature_jobs": {"url": "https://www.nature.com/naturecareers", "category": "academic", "region": "global"},
    "science_careers": {"url": "https://jobs.sciencecareers.org", "category": "academic", "region": "global"},
    "researchgate_jobs": {"url": "https://www.researchgate.net/jobs", "category": "academic", "region": "global"},
    "jobs_ac_uk": {"url": "https://www.jobs.ac.uk", "category": "academic", "region": "uk"},
    "euraxess": {"url": "https://euraxess.ec.europa.eu/jobs", "category": "academic", "region": "europe"},
    
    # === FREELANCE/CONTRACT ===
    "upwork": {"url": "https://www.upwork.com", "category": "freelance", "region": "global"},
    "fiverr": {"url": "https://www.fiverr.com", "category": "freelance", "region": "global"},
    "toptal": {"url": "https://www.toptal.com", "category": "freelance", "region": "global"},
    "freelancer": {"url": "https://www.freelancer.com", "category": "freelance", "region": "global"},
    "guru": {"url": "https://www.guru.com", "category": "freelance", "region": "global"},
    "peopleperhour": {"url": "https://www.peopleperhour.com", "category": "freelance", "region": "global"},
    "99designs": {"url": "https://99designs.com", "category": "freelance", "region": "global"},
    "designcrowd": {"url": "https://www.designcrowd.com", "category": "freelance", "region": "global"},
    "contently": {"url": "https://contently.com", "category": "freelance", "region": "global"},
    "flexjobs_freelance": {"url": "https://www.flexjobs.com/freelance-jobs", "category": "freelance", "region": "global"},
    "solidgigs": {"url": "https://solidgigs.com", "category": "freelance", "region": "global"},
    "cloudpeeps": {"url": "https://www.cloudpeeps.com", "category": "freelance", "region": "global"},
    "working_not_working": {"url": "https://workingnotworking.com", "category": "freelance", "region": "global"},
    "gun_io": {"url": "https://gun.io", "category": "freelance", "region": "global"},
    "x_team": {"url": "https://x-team.com", "category": "freelance", "region": "global"},
    "turing": {"url": "https://www.turing.com", "category": "freelance", "region": "global"},
    "andela": {"url": "https://andela.com", "category": "freelance", "region": "global"},
    
    # === INTERNSHIPS ===
    "wayup": {"url": "https://www.wayup.com", "category": "internship", "region": "global"},
    "internships_com": {"url": "https://www.internships.com", "category": "internship", "region": "global"},
    "chegg_internships": {"url": "https://www.internships.chegg.com", "category": "internship", "region": "global"},
    "youtern": {"url": "https://www.youtern.com", "category": "internship", "region": "global"},
    "internmatch": {"url": "https://www.internmatch.io", "category": "internship", "region": "global"},
    "ripplematch": {"url": "https://ripplematch.com", "category": "internship", "region": "global"},
    "handshake": {"url": "https://joinhandshake.com", "category": "internship", "region": "global"},
    "looksharp": {"url": "https://www.looksharp.com", "category": "internship", "region": "global"},
}

# Company career pages - Top 100 tech companies
COMPANY_CAREER_PAGES = {
    # === FAANG+ ===
    "google": "https://careers.google.com/jobs",
    "meta": "https://www.metacareers.com/jobs",
    "amazon": "https://www.amazon.jobs",
    "apple": "https://www.apple.com/careers",
    "netflix": "https://jobs.netflix.com",
    "microsoft": "https://careers.microsoft.com",
    
    # === AI LEADERS ===
    "openai": "https://openai.com/careers",
    "anthropic": "https://www.anthropic.com/careers",
    "deepmind": "https://deepmind.google/careers",
    "cohere": "https://cohere.com/careers",
    "stability_ai": "https://stability.ai/careers",
    "midjourney": "https://www.midjourney.com/careers",
    "huggingface": "https://huggingface.co/jobs",
    "databricks": "https://www.databricks.com/company/careers",
    "scale_ai": "https://scale.com/careers",
    "anyscale": "https://www.anyscale.com/careers",
    
    # === UNICORNS ===
    "stripe": "https://stripe.com/jobs",
    "airbnb": "https://careers.airbnb.com",
    "uber": "https://www.uber.com/careers",
    "lyft": "https://www.lyft.com/careers",
    "doordash": "https://careers.doordash.com",
    "instacart": "https://instacart.careers",
    "coinbase": "https://www.coinbase.com/careers",
    "robinhood": "https://careers.robinhood.com",
    "plaid": "https://plaid.com/careers",
    "figma": "https://www.figma.com/careers",
    "canva": "https://www.canva.com/careers",
    "notion": "https://www.notion.so/careers",
    "airtable": "https://airtable.com/careers",
    "miro": "https://miro.com/careers",
    "asana": "https://asana.com/jobs",
    "monday": "https://monday.com/careers",
    "clickup": "https://clickup.com/careers",
    "linear": "https://linear.app/careers",
    "vercel": "https://vercel.com/careers",
    "netlify": "https://www.netlify.com/careers",
    "supabase": "https://supabase.com/careers",
    "planetscale": "https://planetscale.com/careers",
    "neon": "https://neon.tech/careers",
    
    # === ENTERPRISE ===
    "salesforce": "https://www.salesforce.com/company/careers",
    "oracle": "https://www.oracle.com/careers",
    "sap": "https://www.sap.com/about/careers.html",
    "servicenow": "https://www.servicenow.com/careers.html",
    "workday": "https://www.workday.com/en-us/company/careers.html",
    "snowflake": "https://careers.snowflake.com",
    "datadog": "https://www.datadoghq.com/careers",
    "splunk": "https://www.splunk.com/en_us/careers.html",
    "elastic": "https://www.elastic.co/careers",
    "mongodb": "https://www.mongodb.com/careers",
    "redis": "https://redis.com/careers",
    "confluent": "https://www.confluent.io/careers",
    "hashicorp": "https://www.hashicorp.com/careers",
    
    # === FINTECH ===
    "square": "https://careers.squareup.com",
    "paypal": "https://www.paypal.com/us/webapps/mpp/jobs",
    "affirm": "https://www.affirm.com/careers",
    "klarna": "https://www.klarna.com/careers",
    "wise": "https://www.wise.jobs",
    "revolut": "https://www.revolut.com/careers",
    "nubank": "https://nubank.com.br/en/careers",
    "chime": "https://www.chime.com/careers",
    "brex": "https://www.brex.com/careers",
    "ramp": "https://ramp.com/careers",
    
    # === CYBERSECURITY ===
    "crowdstrike": "https://www.crowdstrike.com/careers",
    "paloalto": "https://www.paloaltonetworks.com/company/careers",
    "zscaler": "https://www.zscaler.com/careers",
    "okta": "https://www.okta.com/company/careers",
    "cloudflare": "https://www.cloudflare.com/careers",
    "snyk": "https://snyk.io/careers",
    "1password": "https://1password.com/jobs",
    "sentinelone": "https://www.sentinelone.com/careers",
    
    # === CLOUD/INFRA ===
    "docker": "https://www.docker.com/careers",
    "digitalocean": "https://www.digitalocean.com/careers",
    "linode": "https://www.linode.com/company/careers",
    "vultr": "https://www.vultr.com/company/careers",
    "render": "https://render.com/careers",
    "fly_io": "https://fly.io/jobs",
    "railway": "https://railway.app/careers",
    
    # === DEVELOPER TOOLS ===
    "github": "https://github.com/about/careers",
    "gitlab": "https://about.gitlab.com/jobs",
    "atlassian": "https://www.atlassian.com/company/careers",
    "jetbrains": "https://www.jetbrains.com/careers",
    "postman": "https://www.postman.com/company/careers",
    "twilio": "https://www.twilio.com/company/jobs",
    "segment": "https://segment.com/careers",
    "auth0": "https://auth0.com/careers",
    "sentry": "https://sentry.io/careers",
    "launchdarkly": "https://launchdarkly.com/careers",
    
    # === E-COMMERCE ===
    "shopify": "https://www.shopify.com/careers",
    "etsy": "https://careers.etsy.com",
    "ebay": "https://careers.ebayinc.com",
    "wayfair": "https://www.wayfair.com/careers",
    "chewy": "https://careers.chewy.com",
    "wish": "https://careers.wish.com",
    
    # === MEDIA/ENTERTAINMENT ===
    "spotify": "https://www.lifeatspotify.com",
    "discord": "https://discord.com/careers",
    "twitch": "https://www.twitch.tv/jobs",
    "snap": "https://www.snap.com/en-US/jobs",
    "pinterest": "https://www.pinterestcareers.com",
    "reddit": "https://www.redditinc.com/careers",
    "tiktok": "https://careers.tiktok.com",
    "bytedance": "https://jobs.bytedance.com",
    
    # === HEALTH TECH ===
    "epic": "https://careers.epic.com",
    "teladoc": "https://www.teladochealth.com/careers",
    "oscar": "https://www.hioscar.com/careers",
    "ro": "https://ro.co/careers",
    "cerebral": "https://cerebral.com/careers",
    "headspace": "https://www.headspace.com/join-us",
    "calm": "https://www.calm.com/careers",
    
    # === SPACE/HARDWARE ===
    "spacex": "https://www.spacex.com/careers",
    "tesla": "https://www.tesla.com/careers",
    "nvidia": "https://www.nvidia.com/en-us/about-nvidia/careers",
    "amd": "https://www.amd.com/en/corporate/careers",
    "intel": "https://www.intel.com/content/www/us/en/jobs/jobs-at-intel.html",
    "qualcomm": "https://www.qualcomm.com/company/careers",
}

def get_all_job_sources():
    """Return total count and all job sources"""
    total = len(JOB_BOARDS) + len(COMPANY_CAREER_PAGES)
    return {
        "total": total,
        "job_boards": JOB_BOARDS,
        "company_careers": COMPANY_CAREER_PAGES
    }
